-- This file should undo anything in `up.sql`


-- Drop the tables
DROP TABLE IF EXISTS REPLIES;
DROP TABLE IF EXISTS LIKES;
DROP TABLE IF EXISTS FOLLOWERS;
DROP TABLE IF EXISTS USERANALYTICS;
DROP TABLE IF EXISTS TWEETS CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS USERAUTH CASCADE;
